name: movies
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  http: 0.13.3
  carousel_slider: 4.0.0
  shared_preferences: 2.0.7
  provider: 6.0.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.6.0
  firebase_core_web: ^2.11.3
  firebase_auth: ^4.17.3
  go_router: ^13.1.0
  firebase_ui_auth: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
