// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXSEJypPoBeClp6KR7AkKZSyiHljsP5F4',
    appId: '1:860116772302:web:d296ff7fb8a208555b779f',
    messagingSenderId: '860116772302',
    projectId: 'prueba2bim',
    authDomain: 'prueba2bim.firebaseapp.com',
    storageBucket: 'prueba2bim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcS0P_esMBW5449d7thuRmKQWmd7jJhg',
    appId: '1:860116772302:android:8819ae2ec21032135b779f',
    messagingSenderId: '860116772302',
    projectId: 'prueba2bim',
    storageBucket: 'prueba2bim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3WlqNLDo7cezIAGKmLck3agZSYQ_igCk',
    appId: '1:860116772302:ios:1a263616483525e65b779f',
    messagingSenderId: '860116772302',
    projectId: 'prueba2bim',
    storageBucket: 'prueba2bim.appspot.com',
    iosBundleId: 'com.bimsina.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3WlqNLDo7cezIAGKmLck3agZSYQ_igCk',
    appId: '1:860116772302:ios:1a263616483525e65b779f',
    messagingSenderId: '860116772302',
    projectId: 'prueba2bim',
    storageBucket: 'prueba2bim.appspot.com',
    iosBundleId: 'com.bimsina.movies',
  );
}
